#!/bin/sh

VERSION=abrar-test-proj@1.0.28
PROJECT=abrar-test
ENV=production

sentry-cli releases new -p $PROJECT "$VERSION"
# do your build steps here

// both the source files and source maps must be uploaded
sentry-cli releases files "$VERSION" upload-sourcemaps /Users/abhu01/Projects/sentry/sentry-test/dist/scripts/

sentry-cli releases set-commits --auto $VERSION
# once you are done, finalize
sentry-cli releases finalize "$VERSION"

sentry-cli releases deploys "$VERSION" new -e $ENV
